//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranTrongNhan_35011
{
    public partial class TicketVerseMaster
    {
        protected global::System.Web.UI.WebControls.Panel pnlGuest;
        protected global::System.Web.UI.WebControls.Panel pnlUser;
        protected global::System.Web.UI.WebControls.Label lblUserName;
    }
}
