//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranTrongNhan_35011
{
    public partial class TrangChu
    {
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Repeater rptCategories;
        protected global::System.Web.UI.WebControls.Repeater rptHotEvents;
        protected global::System.Web.UI.WebControls.Panel pnlCountdown;
        protected global::System.Web.UI.WebControls.Label lblCountdownTitle;
        protected global::System.Web.UI.WebControls.Label lblCountdownInfo;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkCountdownEvent;
        protected global::System.Web.UI.WebControls.Repeater rptUpcoming;
    }
}
